# Generated by Django 4.1.7 on 2023-05-21 17:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
            ],
            options={
                'db_table': 'TipoAcao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('datainicio', models.DateField(blank=True, db_column='DataInicio', null=True)),
                ('datafim', models.DateField(blank=True, db_column='DataFim', null=True)),
            ],
            options={
                'db_table': 'AnoLetivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categoriasala',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
            ],
            options={
                'db_table': 'CategoriaSala',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('ativo', models.TextField(blank=True, db_column='Ativo', null=True)),
                ('idanoletivo', models.ForeignKey(db_column='AnoLetivoID', null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmanager.anoletivo')),
            ],
            options={
                'db_table': 'Conta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
            ],
            options={
                'db_table': 'EstadoPedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=255, null=True)),
                ('assunto', models.CharField(blank=True, db_column='Assunto', max_length=255, null=True)),
                ('datacriacao', models.DateTimeField(blank=True, db_column='DataCriacao', default=datetime.datetime.now, null=True)),
                ('dataatribuicao', models.DateTimeField(blank=True, db_column='DataAtribuicao', null=True)),
                ('dataresolvido', models.DateTimeField(blank=True, db_column='DataResolvido', null=True)),
                ('dataalvo', models.DateField(blank=True, db_column='DataAlvo', null=True)),
                ('tempoespera', models.CharField(blank=True, db_column='TempoEspera', max_length=255, null=True)),
                ('tempoprocesso', models.CharField(blank=True, db_column='TempoProcesso', max_length=255, null=True)),
                ('motivocancelmento', models.TextField(blank=True, db_column='Cancelamento', null=True)),
                ('anoletivo', models.ForeignKey(blank=True, db_column='AnoLetivo', null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmanager.anoletivo')),
                ('docente', models.ForeignKey(blank=True, db_column='Docente', null=True, on_delete=django.db.models.deletion.CASCADE, to='authmanager.professoruniversitario')),
                ('estado', models.ForeignKey(db_column='EstadoID', on_delete=django.db.models.deletion.CASCADE, to='requestmanager.estadopedido')),
                ('responsavel', models.ForeignKey(blank=True, db_column='Responsavel', null=True, on_delete=django.db.models.deletion.CASCADE, to='authmanager.funcionario')),
            ],
            options={
                'db_table': 'Pedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipoalteracaohorario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
            ],
            options={
                'db_table': 'TipoAlteracaoHorario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipoconta',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
            ],
            options={
                'db_table': 'TipoConta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoPedido',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
            ],
            options={
                'db_table': 'TipoPedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipopedidohorario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
            ],
            options={
                'db_table': 'TipoPedidoHorario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipopedidosala',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
            ],
            options={
                'db_table': 'TipoPedidoSala',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tiporegencia',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
            ],
            options={
                'db_table': 'Tiporegencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoTurma',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
            ],
            options={
                'db_table': 'TipoTurma',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Unidadecurricular',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('periodo', models.CharField(db_column='Periodo', max_length=255, null=True)),
                ('instituicao', models.CharField(db_column='Instituicao', max_length=255, null=True)),
                ('tipo', models.ForeignKey(db_column='TiporegenciaID', null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmanager.tiporegencia')),
            ],
            options={
                'db_table': 'Unidadecurricular',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('edificio', models.CharField(db_column='Edificio', max_length=255)),
                ('sala', models.CharField(db_column='Sala', max_length=255)),
                ('lotacao', models.IntegerField(blank=True, db_column='Lotacao', null=True)),
                ('categoriasalaid', models.ForeignKey(db_column='CategoriaSalaID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='requestmanager.categoriasala')),
                ('idanoletivo', models.ForeignKey(db_column='AnoLetivoID', null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmanager.anoletivo')),
            ],
            options={
                'db_table': 'Sala',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RUC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idanoletivo', models.ForeignKey(db_column='AnoLetivoID', on_delete=django.db.models.deletion.CASCADE, to='requestmanager.anoletivo')),
                ('idconta', models.ForeignKey(db_column='ContaID', on_delete=django.db.models.deletion.CASCADE, to='requestmanager.conta')),
                ('iduc', models.ForeignKey(db_column='UnidadeCurricularID', on_delete=django.db.models.deletion.CASCADE, to='requestmanager.unidadecurricular')),
            ],
            options={
                'db_table': 'RUC',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedidouc',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('assunto', models.CharField(blank=True, db_column='Assunto', max_length=255, null=True)),
                ('acao', models.ForeignKey(db_column='AcaoID', null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmanager.acao')),
                ('pedido_ptr_id', models.ForeignKey(db_column='pedido_ptr_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmanager.pedido')),
                ('tipoturmaid', models.ForeignKey(db_column='TipoTurmaID', null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmanager.tipoturma')),
                ('unidadecurricularid', models.ForeignKey(db_column='UnidadeCurricularID', null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmanager.unidadecurricular')),
            ],
            options={
                'db_table': 'Pedidouc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedidosala',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, db_column='Data', null=True)),
                ('alunosprevistos', models.IntegerField(blank=True, db_column='AlunosPrevistos', null=True)),
                ('horainicio', models.TimeField(blank=True, db_column='HoraInicio', null=True)),
                ('horafim', models.TimeField(blank=True, db_column='HoraFim', null=True)),
                ('acao', models.ForeignKey(db_column='AcaoID', null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmanager.acao')),
                ('categoriasalaid', models.ForeignKey(db_column='CategoriaSalaID', null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmanager.categoriasala')),
                ('pedido_ptr_id', models.ForeignKey(db_column='pedido_ptr_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmanager.pedido')),
                ('tipopedidosalaid', models.ForeignKey(db_column='TipoPedidoSalaID', null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmanager.tipopedidosala')),
            ],
            options={
                'db_table': 'PedidoSala',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedidooutros',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('assunto_pedido', models.CharField(blank=True, db_column='Assunto', max_length=255, null=True)),
                ('descricao_pedido', models.CharField(blank=True, db_column='Descricao', max_length=255, null=True)),
                ('dataalvo_pedido', models.DateField(blank=True, db_column='DataAlvo', null=True)),
                ('pedido_ptr_id', models.ForeignKey(db_column='pedido_ptr_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmanager.pedido')),
            ],
            options={
                'db_table': 'PedidoOutros',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedidohorario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=255, null=True)),
                ('dataorigem', models.DateField(blank=True, db_column='DataOrigem', null=True)),
                ('horaorigem', models.TimeField(db_column='HoraOrigem', null=True)),
                ('datamudanca', models.DateField(blank=True, db_column='DataMundança', null=True)),
                ('horamudanca', models.TimeField(db_column='HoraMudanca', null=True)),
                ('pedido_ptr_id', models.ForeignKey(db_column='pedido_ptr_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmanager.pedido')),
                ('tipoalteracaohorarioid', models.ForeignKey(db_column='TipoAlteracaoHorarioID', null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmanager.tipoalteracaohorario')),
                ('tipopedidohorarioid', models.ForeignKey(db_column='TipoPedidoHorarioID', null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmanager.tipopedidohorario')),
            ],
            options={
                'db_table': 'PedidoHorario',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.ForeignKey(db_column='TipoPedidoID', null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmanager.tipopedido'),
        ),
        migrations.CreateModel(
            name='Dsd',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('turma', models.CharField(blank=True, db_column='Turma', max_length=255, null=True)),
                ('contaid', models.ForeignKey(db_column='ContaID', on_delete=django.db.models.deletion.CASCADE, to='requestmanager.conta')),
                ('idanoletivo', models.ForeignKey(db_column='AnoLetivoID', null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmanager.anoletivo')),
                ('unidadecurricularid', models.ForeignKey(db_column='UnidadeCurricularID', on_delete=django.db.models.deletion.CASCADE, to='requestmanager.unidadecurricular')),
            ],
            options={
                'db_table': 'DSD',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='conta',
            name='tipocontaid',
            field=models.ForeignKey(db_column='TipoContaID', on_delete=django.db.models.deletion.CASCADE, to='requestmanager.tipoconta'),
        ),
        migrations.AddConstraint(
            model_name='dsd',
            constraint=models.UniqueConstraint(fields=('unidadecurricularid', 'turma'), name='aula'),
        ),
    ]
