# Generated by Django 4.1.7 on 2023-05-21 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidohorario',
            name='tipopedidohorarioid',
        ),
        migrations.AddField(
            model_name='pedidohorario',
            name='acao',
            field=models.ForeignKey(db_column='AcaoID', null=True, on_delete=django.db.models.deletion.CASCADE, to='requestmanager.acao'),
        ),
    ]
